### ISSUE TITLE
How to get payload of action?

### ISSUE THREAD

**Issue by ashim-k-saha** [reduxsaga/redux_saga#12]

**Comment by FantasyOR** [comment]
> _No description provided._

Hi =)
can you call generator function with parameters?
```dart
class UserFetchRequested {
  final int id;
  UserFetchRequested(this.id);
}

fetchUser(action) sync* {
  print("fetchUser action: $action");
}

mySaga() sync* {
  print("mySaga");
  yield TakeLatest(fetchUser, pattern: UserFetchRequested);
}
```

i have an errors:
```
I/flutter (15401): NoSuchMethodError: Closure call with mismatched arguments: function 'fetchUser'
I/flutter (15401): Receiver: Closure: (dynamic) => dynamic from Function 'fetchUser': static.
I/flutter (15401): Tried calling: fetchUser()
I/flutter (15401): Found: fetchUser(dynamic) => dynamic
```

what you think about this? any ideas...

**Comment by bilal-uslu** [comment]
Hi,

For using TakeLatest the "action" parameter must be a named parameter;

You should have used like the following

fetchUser(**{dynamic action}**) sync* {
  print("fetchUser action: $action");
}

then it should work

**Comment by FantasyOR** [comment]
Thanks
If i understand correctly: in block **Usage Example** that moment is missed?

![image](https://user-images.githubusercontent.com/3586153/95212256-2b9d2400-07f6-11eb-9bb1-b66559fa0bed.png)

**Comment by bilal-uslu** [comment]
You're absolutely right.

**Comment by bilal-uslu** [comment]
Now fixed. Thanks

**Comment by bilal-uslu** [comment]
Documentation is updated

**Comment by hacker1024** [comment]
When I use a strong type instead of `dynamic`, the action is `null`. This doesn't really make sense, as the type should be known since the watcher was activated from a pattern. This also doesn't play well with the upcoming non-nullable features.

**Comment by bilal-uslu** [comment]
> When I use a strong type instead of `dynamic`, the action is `null`. This doesn't really make sense, as the type should be known since the watcher was activated from a pattern. This also doesn't play well with the upcoming non-nullable features.



> When I use a strong type instead of `dynamic`, the action is `null`. This doesn't really make sense, as the type should be known since the watcher was activated from a pattern. This also doesn't play well with the upcoming non-nullable features.


It has fixed in version 1.1.16

If you have guaranteed your saga will take only one specific type or its derivatives then you can use "usage 2", otherwise it is better to use "usage 1"

//usage 1
fetchUser({dynamic action}) sync* {
...
}

//usage 2
fetchUser({UserFetchRequested action}) sync* {
...
}

mySaga() sync* {
yield TakeEvery(fetchUser, pattern: UserFetchRequested);
}

**Comment by Sylphide** [comment]
Hi,

When I my application is built for the web (through "flutter build web"), the action is null.
Works totally fine in local environment though.

I tried both usage 1 and 2. Any ideas?

**Comment by bilal-uslu** [comment]
Could you please share code?

**Comment by Sylphide** [comment]
Saga
```
authRequest({AuthRequest action}) sync* {
    yield Try(() sync* {
      print('action is $action'); // action null if application is built
      AuthClient authClient = action.authClient;
      yield Call(authClient.login);
      yield Put(AuthSuccess(authClient));
    }, Catch: (e) sync* {
      print('Auth failed $e');
      yield Put(AuthFailed(e));
    });
  }

  watchAuthRequest() sync* {
    yield TakeLatest(authRequest, pattern: AuthRequest);
  }
```
Widget
```
...
      onInit: (store) {
        if(store.state.authState.authClient == null) {
          AuthConfig config = AuthConfig.fromJson(GlobalConfiguration().getValue("auth"));
          final AuthClient authClient = AuthClient(config);
          store.dispatch(AuthRequest(authClient));
        }
      }
...
```

**Comment by Sylphide** [comment]
I think I found the issue:

In takeLatest.dart

```
Iterable<Effect> _TakeLatest(Function saga,
    {List<dynamic> args,
    Map<Symbol, dynamic> namedArgs,
    Function Catch,
    Function Finally,
    Channel channel,
    dynamic pattern,
    String name}) sync* {
  var forkedTask = Result<Task>();

  while (true) {
    var action = Result<dynamic>();
    yield Take(pattern: pattern, channel: channel, result: action);

    if (forkedTask.value != null) {
      yield Cancel([forkedTask.value]);
    }

    yield Fork(saga,
        args: args,
        namedArgs: _functionHasActionArgument(saga) // Function here returns false when built
            ? <Symbol, dynamic>{
                ...?namedArgs,
                #action: action is Result ? action.value : action
              }
            : namedArgs,
        Catch: Catch,
        Finally: Finally,
        name: name,
        result: forkedTask);
  }
}
```

The `_functionHasActionArgument` returns incorrectly false when the application is built.

And in functions.dart

```
bool _functionHasActionArgument(Function f) {
  var closure = f.toString();
  return closure.contains(' action}') || closure.contains(' action,');
}
```

When application is running in local
closure = 'Closure: ({AuthRequest action}) => dynamic from: function() { [native code] }'

And when application is built
closure = Closure 'DB' of Instance of 'minified:H1'

**Comment by bilal-uslu** [comment]
Yes. you are right. The reason is minification. I am gonna to release new version. Almost fixed

**Comment by bilal-uslu** [comment]
@Sylphide could you please test again with version 2.0.0 
you should change pubspec.yaml 
and change version 
redux_saga: ^2.0.0
and 
pub get

Hope it is resolved.

Dont forget to check change log

at v2.0.0 there are changes about Catch and TakeEvery usages

**Comment by Sylphide** [comment]
@bilal-uslu Works fine with the new 2.0.0. Thank you very much

**Comment by bilal-uslu** [comment]
Perfect. Your welcome. Enjoy

**Comment by hacker1024** [comment]
Is there a way to do this with a regular `Take` effect?
Here, `_login` and `_logout` are generators, and I'd like to be able to access the action in them.

```dart
while (true) {
  yield Take(pattern: LoginRequested);
  yield Call(_login);
  yield Take(pattern: LogoutRequested);
  yield Call(_logout);
}
```

**Comment by bilal-uslu** [comment]
//while Taking action
var action = Result();
yield Take(pattern: LoginRequested, result: action);
//now you have the action with payload

//while calling (ensure arguments exists at the function)
yield Call(_login, args: [action.value]);
