### ISSUE TITLE
flutter pub get is failing

### ISSUE THREAD

**Issue by ashim-k-saha** [reduxsaga/redux_saga#16]
[todo] flutter pub get
Running "flutter pub get" in todo...                   
Because every version of redux_saga depends on redux ^4.0.0 and todo depends on redux ^5.0.0, redux_saga is forbidden.

So, because todo depends on redux_saga ^2.0.2, version solving failed.
pub get failed (1; So, because todo depends on redux_saga ^2.0.2, version solving failed.)
exit code 1

**Comment by bilal-uslu** [comment]
Now redux_saga 2.1.0 is avaliable on pub.dev
Versions are updated also
Thanks for the contribution

**Comment by ashim-k-saha** [comment]
Thanks :)
