### ISSUE TITLE
Roadmap for Null safety

### ISSUE THREAD

**Issue by ashim-k-saha** [reduxsaga/redux_saga#19]
Is there a roadmap for `null safety` in `redux_saga`?

**Comment by lukepighetti** [comment]
Subscribed

**Comment by bilal-uslu** [comment]
still working on it

**Comment by bilal-uslu** [comment]
redux_saga 3.0.3 version is now null safe and available on pub.dev

**Comment by ashim-k-saha** [comment]
Thanks
