### ISSUE TITLE
Debugging of saga!

### ISSUE THREAD

**Issue by ashim-k-saha** [reduxsaga/redux_saga#26]
Most of the time when I am trying to debug the saga, the cursor could not stop at the breakpoint. Is there anything I am missing?

**Comment by bilal-uslu** [comment]
There is nothing other than an ordinary code debug. I suggest to check the environment and your code logic. If everything seems fine, you can try to debug this [example](https://github.com/reduxsaga/shopping_cart) app. Try on ios,android,web.
Still face problems than please post the failing code pattern. Also provide which env the debug goes (ios,android,web...)
