### ISSUE TITLE
When error happens, all other API request cease to work

### ISSUE THREAD

**Issue by Nerogee** [reduxsaga/redux_saga#28]
I use redux_saga for my project and it is really a nice plugin. 

Occasionally, I found when error happens (for example, due to calling setState for widget that no longer appears in the widget tree) during API call wrapped in saga, following up API request will all cease to work. When such an error happen, the only thing to get it back to normal is killing the app and launch it again. This is very bad for user experience. 

As I pointed it out, reason of such errors is  part of my coding issue. But I only expect it affect only that certain action. but no all other API calls. **I'm not sure if there is a mechanism to prevent a certain failure from affecting the whole app (more accurately the saga system itself)**.  Or maybe I don't use saga in a correct way. Please help. thanks.

`flutter: setState() called after dispose(): _CompetitionTeamDetailState#87ce4(lifecycle state: defunct, not mounted)
This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
flutter: #0      State.setState.<anonymous closure> (package:flutter/src/widgets/framework.dart:1052:9)
#1      State.setState (package:flutter/src/widgets/framework.dart:1087:6)
#2      _CompetitionTeamDetailState.mappingTeamParticipantObject (package:MYPACKAGENAME/screen/CompetitionTeamDetail.dart:638:7)
#3      _CompetitionTeamDetailState.fetchTeamMember.<anonymous closure> (package:MYPACKAGENAME/screen/CompetitionTeamDetail.dart:745:9)
#4      fetchMyCompetitionTeamMemberDetail.<anonymous closure> (package:MYPACKAGENAME/redux/saga.dart:3631:16)
#5      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:183:26)
#6      _taskRunner.next (package:redux_saga/src/taskRunner.dart:223:63)
#7      _TaskCallback.next (package:redux_saga/src/taskCallback.dart:18:16)
#8      _taskRunner.digestEffect.<anonymous closure> (package:redux_saga/src/taskRunner.dart:346:16)
#9      _TaskCallback.next (package:redux_saga/src/taskCallback.dart:18:16)
#10     Put._run.<anonymous closure> (package:redux_saga/src/effects/put.dart:59:12)
#11     _exec (package:redux_saga/src/scheduler.dart:28:9)
#12     _flush (package:redux_saga/src/scheduler.dart:70:5)
#13     asap (package:redux_saga/src/scheduler.dart:40:5)
#14     Put._run (package:redux_saga/src/effects/put.dart:41:5)
#15     _taskRunner.runEffect (package:redux_saga/src/taskRunner.dart:301:14)
#16     _taskRunner.digestEffect (package:redux_saga/src/taskRunner.dart:371:19)
#17     _taskRunner.next (package:redux_saga/src/taskRunner.dart:249:9)
#18     _TaskCallback.next (package:redux_saga/src/taskCallback.dart:18:16)
#19     _taskRunner.digestEffect.<anonymous closure> (package:redux_saga/src/taskRunner.dart:346:16)
#20     _TaskCallback.next (package:redux_saga/src/taskCallback.dart:18:16)
#21     _resolveFuture.<anonymous closure> (package:redux_saga/src/resolve.dart:4:37)
#22     _rootRunUnary (dart:async/zone.dart:1436:47)
#23     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
<asynchronous suspension>
flutter: This widget has been unmounted, so the State no longer has a context (and should be considered defunct).
Consider canceling any active work during "dispose" or using the "mounted" getter to determine if the State is still active.
flutter: #0      State.context.<anonymous closure> (package:flutter/src/widgets/framework.dart:909:9)
#1      State.context (package:flutter/src/widgets/framework.dart:915:6)
#2      _CompetitionTeamDetailState.fetchTeamMember.<anonymous closure> (package:MYPACKAGENAME/screen/CompetitionTeamDetail.dart:747:30)
#3      fetchMyCompetitionTeamMemberDetail.<anonymous closure> (package:MYPACKAGENAME/redux/saga.dart:3639:14)
#4      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:183:26)
#5      _taskRunner.next (package:redux_saga/src/taskRunner.dart:223:63)
#6      _TaskCallback.next (package:redux_saga/src/taskCallback.dart:18:16)
#7      _taskRunner.processFunctionReturn (package:redux_saga/src/taskRunner.dart:168:16)
#8      _taskRunner.switchToOnError (package:redux_saga/src/taskRunner.dart:134:7)
#9      _taskRunner.next (package:redux_saga/src/taskRunner.dart:263:9)
#10     _TaskCallback.next (package:redux_saga/src/taskCallback.dart:18:16)
#11     _taskRunner.digestEffect.<anonymous closure> (package:redux_saga/src/taskRunner.dart:346:16)
#12     _TaskCallback.next (package:redux_saga/src/taskCallback.dart:18:16)
#13     Put._run.<anonymous closure> (package:redux_saga/src/effects/put.dart:59:12)
#14     _exec (package:redux_saga/src/scheduler.dart:28:9)
#15     _flush (package:redux_saga/src/scheduler.dart:70:5)
#16     asap (package:redux_saga/src/scheduler.dart:40:5)
#17     Put._run (package:redux_saga/src/effects/put.dart:41:5)
#18     _taskRunner.runEffect (package:redux_saga/src/taskRunner.dart:301:14)
#19     _taskRunner.digestEffect (package:redux_saga/src/taskRunner.dart:371:19)
#20     _taskRunner.next (package:redux_saga/src/taskRunner.dart:249:9)
#21     _TaskCallback.next (package:redux_saga/src/taskCallback.dart:18:16)
#22     _taskRunner.digestEffect.<anonymous closure> (package:redux_saga/src/taskRunner.dart:346:16)
#23     _TaskCallback.next (package:redux_saga/src/taskCallback.dart:18:16)
#24     _resolveFuture.<anonymous closure> (package:redux_saga/src/resolve.dart:4:37)
#25     _rootRunUnary (dart:async/zone.dart:1436:47)
#26     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
<asynchronous suspension>

#0      The above error occurred in task saga#484 
#1       created by saga#482
#2       created by saga#244
#3       created by saga#243
#4       created by saga#1
#5      Tasks cancelled due to error:
#6       saga#244
#7       saga#3
#8       saga#6
#9       saga#9
#10       saga#12
#11       saga#15
#12       saga#18
#13       saga#21
#14       saga#24
#15       saga#27
#16       saga#30
#17       saga#33
#18       saga#36
#19       saga#39
#20       saga#42
#21       saga#45
#22       saga#48
#23       saga#51
#24       saga#54
#25       saga#57
#26       saga#60
#27       saga#63
#28       saga#66
#29       saga#69
#30       saga#72
#31       saga#75
#32       saga#78
#33       saga#81
#34       saga#84
#35       saga#87
#36       saga#90
#37       saga#93
#38       saga#96
#39       saga#99
#40       saga#102
#41       saga#105
#42       saga#108
#43       saga#111
#44       saga#114
#45       saga#117
#46       saga#120
#47       saga#123
#48       saga#126
#49       saga#129
#50       saga#132
#51       saga#135
#52       saga#138
#53       saga#141
#54       saga#144
#55       saga#147
#56       saga#150
#57       saga#153
#58       saga#156
#59       saga#159
#60       saga#162
#61       saga#165
#62       saga#168
#63       saga#171
#64       saga#174
#65       saga#177
#66       saga#180
#67       saga#183
#68       saga#186
#69       saga#189
#70       saga#192
#71       saga#195
#72       saga#198
#73       saga#201
#74       saga#204
#75       saga#207
#76       saga#210
#77       saga#213
#78       saga#216
#79       saga#219
#80       saga#222
#81       saga#225
#82       saga#228
#83       saga#231
#84       saga#234
#85       saga#237
#86       saga#240
#87       saga#246
#88       saga#249
#89       saga#252
#90       saga#255
#91       saga#258
#92       saga#261
#93       saga#264
#94       saga#267
#95       saga#270
#96       saga#273
#97       saga#276
#98       saga#279
#99       saga#282
#100       saga#285
#101       saga#288
#102       saga#291`

**Comment by Nerogee** [comment]
There are similar report on stackoverflow [https://stackoverflow.com/questions/48423464/redux-saga-stops-after-error](url) . The different is that one in reactjs. Mine is with Flutter.

**Comment by bilal-uslu** [comment]
Either, you can provide Catch and Finally Sagas at 

sagaMiddleware.run(rootSaga);

//function signature
  Task run(Function saga,
      {List<dynamic> args,
      Map<Symbol, dynamic> namedArgs,
      Function Catch,
      Function Finally,
      String name});

Or wrap before yield all with

  yield Try(() sync* {
...
  }, Catch: (e, s) sync* {
...
  });

If you provide me sample code to reproduce the issue maybe It is possible to help more.

**Comment by Nerogee** [comment]
@bilal-uslu thanks for the reply. I did have the whole wrapped in try-catch block. just like the second method you showed above.  One important thing i miss from the issue description is that the **exception** thrown from the **Catch** block itself. And there is not other place this can be caught again in my case. When error propagate to the saga root, the whole saga tree will stop working and fail to handle further task.

My solution at last is to add another error handler in the yield TakeLastest function. such as 

`yield TakeLatest(FUNCTION, pattern:**PATTERN, Catch: onSagaErrorHandler);`

**Comment by bilal-uslu** [comment]
Catching directly through the Effect can be another option.
Actually, When an unhandled exception occurs in a Forked Task (here TakeLatest is a Froked Task) it propagates.
In some cases, it propagates to the root if not handled at all.
But Spawned tasks do not propagate and continue to function. 
As another option, you can pass detached: false to TakeLatest to make it a Spawned task.
Or, you can catch it like the following example. If you uncomment the line at the saga "incrementAsync" and rethrow the exception you see both TakeLatest will stop (because they are Froked by default) but the Spawned task will remain to function. 
If there is another case to reproduce the problem you've faced I am happy to help you out.


`import 'package:redux/redux.dart';
import 'package:redux_saga/redux_saga.dart';

// Reducer method
// Changes state according to the actions dispatched
int counterReducer(int state, dynamic action) {
  if (action is IncrementAction) {
    return state + 1;
  } else if (action is DecrementAction) {
    return state - 1;
  }

  return state;
}

//Actions
class IncrementAction {}

class DecrementAction {}

class IncrementAsyncAction {}

//incrementAsync Saga increasing count delayed
Iterable incrementAsync({dynamic action}) sync* {
  yield Try(() sync* {
    print('incrementAsync');
    throw Exception('error');
  }, Catch: (Exception e, StackTrace s) sync* {
    //throw e; //uncomment to see error propogation 
  });
}

Iterable incrementAsync2({dynamic action}) sync* {
  print('incrementAsync2');
}

// counterSaga takes every IncrementAsyncAction
// action and forks incrementAsync
Iterable counterSaga() sync* {
//  yield TakeEvery(incrementAsync, pattern: IncrementAsyncAction);
  var i=0;
  while(true) {
    i++;

    yield Delay(Duration(seconds: 1));
    print('counting ' + i.toString());

    if (i % 5 == 0 )  {
      yield Put(IncrementAsyncAction());
    }
  }
}

Iterable rootSaga() sync* {
//  yield TakeEvery(incrementAsync, pattern: IncrementAsyncAction);
  yield All(<Symbol,Effect>{
    #call1 : Spawn(counterSaga),
    #call2 : TakeLatest(incrementAsync, pattern: IncrementAsyncAction),
    #call3 : TakeLatest(incrementAsync2, pattern: IncrementAsyncAction),
  });
}

void main() {
  // create middleware
  var sagaMiddleware = createSagaMiddleware();

  // create store and apply middleware
  final store = Store<int>(
    counterReducer,
    initialState: 0,
    middleware: [applyMiddleware(sagaMiddleware)],
  );

  // attach store
  sagaMiddleware.setStore(store);

  // run root saga
  sagaMiddleware.run(rootSaga);

  //subscribe to the store
  store.onChange.listen(render);
}

//this method may render the ui according to the store data
//now it is just printing to the console for every change
void render(int state) {
  print(state);
}
`

**Comment by Nerogee** [comment]
thank you so much @bilal-uslu for such a detailed explanation. The **Spawn** method sounds like a nice solution. I will give it a try in my project.
