### ISSUE TITLE
is there a way to return a value from a future function using Fork?

### ISSUE THREAD

**Issue by chirastefan** [reduxsaga/redux_saga#30]
I have a function that returns `Future<Map<String, SomeClass>>` and I can call this with
```
yield Call(myFunction, args:[someArgs], result: myFuncRes)
```
but `Call` is blocking and I want to have this function be called with `Fork` -  non blocking, but when I do this I get this error
`type '_Task' is not a subtype of type Map<String, SomeClass>`

**Comment by bilal-uslu** [comment]
You can check the following example for how to use Future returning functions, https://github.com/reduxsaga/shopping_cart/blob/master/lib/sagas/index.dart
